/**
 * nudify.pics — Gallery-first. Images dominate above the fold.
 * Amber/orange theme. Visual, image-heavy.
 */
import type { DomainConfig } from '@/config/domains'
import CTAButton from '@/components/CTAButton'
import FAQAccordion from '@/components/FAQAccordion'
import BeforeAfterSlider from '@/components/BeforeAfterSlider'
import ImagePlaceholder from '@/components/ImagePlaceholder'

const HAS_IMAGES = true

export default function LayoutGallery({ cfg }: { cfg: DomainConfig }) {
  const faqs = cfg.subpages.find(sp => sp.slug === 'faq')?.faqs.slice(0, 6) ?? []

  return (
    <div className="bg-[#0a0800] text-white">
      {/* COMPACT HERO */}
      <section className="pt-16 pb-10 px-6 text-center relative overflow-hidden">
        <div className="absolute inset-0 pointer-events-none"
          style={{ background: `radial-gradient(ellipse 80% 40% at 50% 0%, ${cfg.primaryHex}28, transparent)` }} />
        <div className="relative z-10 max-w-2xl mx-auto">
          <h1 className="text-4xl md:text-6xl font-black tracking-tight mb-4 leading-tight">
            {cfg.heroHeadline}
          </h1>
          <p className="text-gray-400 mb-8 text-base">{cfg.heroSubheadline}</p>
          <div className="flex flex-wrap gap-3 justify-center">
            <CTAButton href={cfg.ctaUrl} label={cfg.ctaText} hex={cfg.primaryHex} size="md" />
            <div className="flex items-center gap-2 px-5 py-3 rounded-xl bg-white/5 border border-white/10 text-sm text-gray-400">
              {cfg.stats.slice(0,2).map((s,i) => (
                <span key={i}>{i>0 && <span className="mx-2 text-white/20">·</span>}<strong style={{ color: cfg.accentHex }}>{s.value}</strong> {s.label}</span>
              ))}
            </div>
          </div>
          <p className="text-xs text-gray-600 mt-4">Free to start · No subscription required</p>
        </div>
      </section>

      {/* GALLERY GRID — the main event */}
      <section className="px-4 pb-16">
        <div className="max-w-6xl mx-auto">
          <p className="text-center text-sm text-gray-500 mb-6">← Drag sliders to compare · All results generated by AI</p>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
            {[1,2,3,4,5,6].map(n => HAS_IMAGES
              ? <BeforeAfterSlider key={n} beforeSrc={`/images/before-${n}.webp`} afterSrc={`/images/after-${n}.webp`} height={320} />
              : <div key={n} className="rounded-xl overflow-hidden grid grid-cols-2 gap-0.5">
                  <ImagePlaceholder label="BEFORE" aspectRatio="3/4" className="rounded-none" />
                  <ImagePlaceholder label="AFTER" aspectRatio="3/4" className="rounded-none" />
                </div>
            )}
          </div>
          <div className="text-center mt-10">
            <CTAButton href={cfg.ctaUrl} label="Generate Your Own Pics Free" hex={cfg.primaryHex} size="lg" />
          </div>
        </div>
      </section>

      {/* FEATURES — icon list */}
      <section className="py-16 px-6 bg-white/[0.02]">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-2xl font-black mb-8 text-center">Everything you need</h2>
          <div className="grid sm:grid-cols-2 md:grid-cols-3 gap-3">
            {cfg.features.map(f => (
              <div key={f.title} className="flex items-start gap-3 p-4 rounded-xl bg-white/[0.03] border border-white/8">
                <span className="text-xl flex-shrink-0">{f.icon}</span>
                <div>
                  <p className="text-sm font-semibold text-white">{f.title}</p>
                  <p className="text-xs text-gray-500 mt-0.5">{f.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* HOW IT WORKS */}
      <section className="py-16 px-6">
        <div className="max-w-3xl mx-auto">
          <h2 className="text-2xl font-black mb-10 text-center">How to generate nude AI pics</h2>
          <div className="space-y-4">
            {[
              { n: 1, title: 'Upload a photo', desc: 'Any JPG, PNG or WebP image up to 10MB.' },
              { n: 2, title: 'Select a style', desc: '19 styles — from bikini to explicit NSFW.' },
              { n: 3, title: 'Get your pics', desc: 'Under 10 seconds. Free retry if needed.' },
            ].map(step => (
              <div key={step.n} className="flex gap-5 p-5 rounded-xl border border-white/10 bg-white/[0.02]">
                <div className="w-10 h-10 rounded-full flex items-center justify-center font-black text-lg flex-shrink-0"
                  style={{ background: cfg.primaryHex }}>
                  {step.n}
                </div>
                <div>
                  <h3 className="font-bold text-white">{step.title}</h3>
                  <p className="text-gray-500 text-sm mt-0.5">{step.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FREE CTA */}
      <section className="py-16 px-6"
        style={{ background: `linear-gradient(135deg, ${cfg.primaryHex}18, transparent)` }}>
        <div className="max-w-xl mx-auto text-center">
          <h2 className="text-3xl font-black mb-3">Start generating free</h2>
          <p className="text-gray-400 text-sm mb-8">5 free AI nude pics every day. No subscription, no credit card needed.</p>
          <CTAButton href={cfg.ctaUrl} label={cfg.ctaText} hex={cfg.primaryHex} size="lg" />
        </div>
      </section>

      {/* FAQ */}
      {faqs.length > 0 && (
        <section className="py-16 px-6">
          <div className="max-w-3xl mx-auto">
            <h2 className="text-2xl font-black mb-8 text-center">Questions</h2>
            <FAQAccordion faqs={faqs} hex={cfg.primaryHex} />
          </div>
        </section>
      )}
    </div>
  )
}
